image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: latest
rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672"
replicas: 2
env:
  NODE_ENV: "development"
httproute:
  namespace: vkpaints-dev-ns
  gatewayName: vk-paints-gateway
  gatewayNamespace: vkpaints-gateway-ns
  hostname: dev.vkcolors.shop
  path: /api/notifications
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: notification-service
          topologyKey: "kubernetes.io/hostname"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

startupProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  failureThreshold: 30
  periodSeconds: 10

initContainers:
  - name: wait-for-rabbitmq
    image: busybox:1.28
    command: ['sh', '-c', 'until nc -zv rabbitmq.vkpaints-dev-ns.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 2; done;']


