image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: latest
rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672"
replicas: 2
env:
  NODE_ENV: "development"
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: notification-service
          topologyKey: "kubernetes.io/hostname"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
