image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
service:
  port: 80
  targetPort: 3000

httproute:
  gatewayName: vk-paints-gateway
  gatewayNamespace: vkpaints-gateway-ns
  path: /api/notifications

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: notification-service
        topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 20
readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

startupProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  failureThreshold: 30
  periodSeconds: 10
initContainers: []


