image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: v1.1.0
replicas: 2
env:
  NODE_ENV: "production"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: notification-service
      topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: false
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  enabled: false
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10


startupProbe:
  enabled: false
  httpGet:
    path: /health
    port: 3000
  failureThreshold: 30
  periodSeconds: 10
initContainers:
  - name: wait-for-rabbitmq
    image: busybox:1.28
    command: ['sh', '-c', 'until nc -zv rabbitmq.vkpaints-prod-ns.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 2; done;']
