image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: v1.1.0
replicas: 2
env:
  NODE_ENV: "production"

httproute:
  namespace: vkpaints-prod-ns
  gatewayName: vk-paints-gateway
  gatewayNamespace: vkpaints-gateway-ns
  hostname: vkcolors.shop
  path: /api/notifications

rabbitmq:
  url: "amqp://guest:guest@rabbitmq.vkpaints-prod-ns.svc.cluster.local:5672"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: notification-service
        topologyKey: "kubernetes.io/hostname"

resources:
  requests:
    memory: "256Mi"
    cpu: 100m
  limits:
    memory: "512Mi"
    cpu: 500m

livenessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10


startupProbe:
  enabled: true
  httpGet:
    path: /actuator/health
    port: 8080
  failureThreshold: 30
  periodSeconds: 10
initContainers: []


