image:
  repository: ghcr.io/vk-paints/vkpaints-notification-service
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
service:
  port: 80

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: notification-service
      topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  exec:
    command:
    - sh
    - -c
    - "ps aux | grep 'node' | grep -v grep"
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  exec:
    command:
    - sh
    - -c
    - "ps aux | grep 'node' | grep -v grep"
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
