global:
  namespace: vkpaints-dev-ns
  gatewayNamespace: vkpaints-gateway-ns
  storageClassName: vkpaints-nfs-sc
  imagePullSecrets:
    - name: regcred

# NFS CSI Settings
nfs:
  server: 15.206.155.254
  share: /var/nfs/vkpaints

postgres:
  enabled: true
  image: postgres:15-alpine
  storage: 3Gi
  user: postgres
  password: postgres

rabbitmq:
  enabled: true
  image: rabbitmq:3-management-alpine
  storage: 3Gi

gateway:
  service:
    type: NodePort
    nodePort: 30080
