global:
  namespace: vkpaints-prod-ns
  gatewayNamespace: vkpaints-gateway-ns
  storageClassName: premium-rwo # Using SSD for production storage class

microservices:
  frontend:
    image: ghcr.io/vk-paints/vkpaints-frontend-service:main
    port: 8080
  user:
    image: ghcr.io/vk-paints/vkpaints-user-service:main
    port: 3001
  product:
    image: ghcr.io/vk-paints/vkpaints-product-service:main
    port: 3002
  quotation:
    image: ghcr.io/vk-paints/vkpaints-quotation-service:main
    port: 3003
  order:
    image: ghcr.io/vk-paints/vkpaints-order-service:main
    port: 3004
    env:
      RABBITMQ_URL: "amqp://rabbitmq"
  retailer:
    image: ghcr.io/vk-paints/vkpaints-retailer-service:main
    port: 3005
  notification:
    image: ghcr.io/vk-paints/vkpaints-notification-service:main
    port: 3000
    env:
      RABBITMQ_URL: "amqp://rabbitmq"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "465"
      SMTP_SECURE: "true"
