global:
  namespace: vkpaints-dev-ns
  gatewayNamespace: vkpaints-gateway-ns
  storageClassName: vkpaints-nfs-sc # Using custom NFS storage class
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 70
nfs:
  server: 15.206.155.254
  share: /var/nfs/vkpaints

gateway:
  service:
    type: NodePort
    nodePort: 30080
