image:
  repository: ghcr.io/vk-paints/vkpaints-frontend-service
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
replicas: 2
service:
  port: 80

httproute:
  gatewayName: vk-paints-gateway
  gatewayNamespace: vkpaints-gateway-ns
  path: /

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: frontend
      topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
