image:
  repository: ghcr.io/vk-paints/vkpaints-user-service
  tag: ""
replicas: 2
env:
  NODE_ENV: "development"

httproute:
  namespace: vkpaints-dev-ns
  hostname: dev.vkcolors.shop

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: user-service
      topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
