image:
  repository: ghcr.io/vk-paints/vkpaints-user-service
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
service:
  port: 80
  targetPort: 3001

httproute:
  gatewayName: vk-paints-gateway
  gatewayNamespace: vkpaints-gateway-ns
  path: /api/users

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: user-service
        topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

startupProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3001
  failureThreshold: 30
  periodSeconds: 10
initContainers: []
