image:
  repository: ghcr.io/vk-paints/vkpaints-order-service
  tag: latest
db:
  url: "postgres://postgres:postgres@postgres:5432/order_db"
rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672"
replicas: 2
env:
  NODE_ENV: "development"
httproute:
  namespace: vkpaints-dev-ns
  hostname: dev.vkcolors.shop
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: order-service
        topologyKey: "kubernetes.io/hostname"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /health
    port: 3004
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
