image:
  repository: ghcr.io/vk-paints/vkpaints-quotation-service
  tag: latest
service:
  targetPort: 3003
db:
  url: "postgres://postgres:postgres@postgres:5432/quotation_db"
replicas: 2
env:
  NODE_ENV: "development"
httproute:
  namespace: vkpaints-dev-ns
  hostname: dev.vkcolors.shop
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: quotation-service
          topologyKey: "kubernetes.io/hostname"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /health
    port: 3003
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /health
    port: 3003
  initialDelaySeconds: 5
  periodSeconds: 10
