image:
  repository: ghcr.io/vk-paints/vkpaints-retailer-service
  tag: v1.1.0
replicas: 2
env:
  NODE_ENV: "production"
httproute:
  namespace: vkpaints-prod-ns
  hostname: vkcolors.shop

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: retailer-service
      topologyKey: "kubernetes.io/hostname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3005
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3005
  initialDelaySeconds: 5
  periodSeconds: 10

startupProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3005
  failureThreshold: 30
  periodSeconds: 10
initContainers:
  - name: wait-for-postgres
    image: busybox:1.28
    command: ['sh', '-c', 'until nc -zv postgres.vkpaints-prod-ns.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done;']
