apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: {{ .Values.global.gatewayNamespace | default "vkpaints-gateway-ns" }}
  labels:
    app: argocd
spec:
  parentRefs:
    - name: vkpaints-gateway
      namespace: {{ .Values.global.gatewayNamespace | default "vkpaints-gateway-ns" }}
  hostnames:
    - "argocd-dev.vkcolors.shop"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
