apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    shared-gateway: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.gatewayNamespace }}
