apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
  namespace: {{ .Values.global.namespace }}
data:
  init.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE product_db;
    CREATE DATABASE quotation_db;
    CREATE DATABASE order_db;
    CREATE DATABASE retailer_db;
