apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        - secretRef:
            name: {{ .Chart.Name }}-secret
        ports:
        - containerPort: {{ .Values.service.targetPort | default 3000 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          {{- toYaml (omit .Values.startupProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 10 }}
        {{- end }}
